### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by wrunion** [MitanshiKshatriya/taylor-swift-api#6]
It looks like the Heroku server is down. I know Heroku's TOS changed a few days ago; maybe that's why? 

I'd love to use this if it's able to come back online! Nice work!

**Comment by MitanshiKshatriya** [comment]
@wrunion thanks!

Yes it's because of no free dynos are available. I am trying few free hosting services to bring it back up. Do you have any suggestions?

**Comment by MitanshiKshatriya** [comment]
It's up at https://taylorswiftapi.onrender.com/
But would love to know if you have suggestions regarding hosting or in general
